name: build
on:
  push:
    branches:
      - main
    paths:
      - '**.lock'
      - 'package-lock.json'
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/afdesk/sarif-demo:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/afdesk/sarif-demo:${{ github.sha }}'
          format: 'template'
          template: '@sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: 'trivy-results.sarif'
          path: 'trivy-results.sarif'
          retention-days: 5