---
name: PR

on:
  pull_request:
    branches: [main]
    paths:
      - '**.lock'
      - 'package-lock.json'

jobs:

  build:
    name: PR
    runs-on: ubuntu-18.04
    steps:
      - name: trivy - fs
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@./sarif.tpl'
          output: 'trivy-results.sarif'
          exit-code: 0

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: 'trivy-results.sarif'
          path: 'trivy-results.sarif'
          retention-days: 5      